version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dockerdb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  web:
    build: ./web
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./web:/var/www/html
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
